### ISSUE TITLE
Please link to the JWT spec

### ISSUE THREAD

**Issue by mook** [mozilla/id-specs#20]
Both the dev and prod versions of browserid/index.md do not appear to actually ever explain what JWT is. It would be probably be useful to link to the relevant spec (and expand the initialism at first mention); it appears to be [JSON Web Token](http://datatracker.ietf.org/doc/draft-ietf-oauth-json-web-token/)?

**Comment by callahad** [comment]
@warner to dig up and add the correct link

**Comment by djc** [comment]
There's a bit of an issue here in that there's no final link for this yet. Supposedly we'd link to the last draft published so far?
