### ISSUE TITLE
Decide if expiration &c times are milliseconds or seconds from epoch

### ISSUE THREAD

**Issue by mook** [mozilla/id-specs#21]
Currently, the spec defers to [JWT](http://datatracker.ietf.org/doc/draft-ietf-oauth-json-web-token/) for expiry / etc times; that spec defines them to be IntDate, which is seconds from epoch.  However, the current implementations appear to assume it's call milliseconds-from-epoch (passing it directly to the JavaScript [Date](https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/Date) constructor).

Please either change the spec to say milliseconds (deviating from JWT) or change the implementations to use seconds :)

**Comment by warner** [comment]
good catch! I think we'll stick with the current implementation, and update the spec to make it clear that it's ms-since-epoch. We should consider switching to seconds in a future version of the assertion format, though, to bring us in line with JWT.

**Comment by callahad** [comment]
Fixed by #25. Thanks!

**Comment by warner** [comment]
yeah, current behavior uses ms-since-epoch, and #25 updated the docs to match, so that's what we'll go with for now. The next revision of the cert format should use seconds-since-epoch, and should match JWT.
