### ISSUE TITLE
The string 'host-meta file' is not defined.

### ISSUE THREAD

**Issue by akumria** [mozilla/id-specs#22]
In the following paragraph:

> Declaring Support and Parameters for BrowserID
> 
> To declare support for BrowserID, a domain MUST publish either a BrowserID support document OR a BrowserID 
> delegated-support document at a specific URI relative to the domain's SSL URI. The relative reference URI for this 
> document is /.well-known/browserid, as per RFC5785. The domain MAY choose to reference this BrowserID support
> document from a host-meta file (as per RFC5785)."

The string 'host-meta file' is nowhere in RFC5785.

Clarifying precisely what you mean would be helpful.

**Comment by sanduhrs** [comment]
Web Host Metadata RFC6415 defines the "host-meta file"
http://tools.ietf.org/html/rfc6415

**Comment by akumria** [comment]
OK - I guess the parenthetical RFC reference should be updated to 6415 then.

**Comment by callahad** [comment]
I'm dedicating much of Thursday to hacking on id-specs. This should get cleared up then or shortly thereafter.
