### ISSUE TITLE
merge beta1 into prod

### ISSUE THREAD

**Issue by ozten** [mozilla/id-specs#26]
Now that beta1 shipped, I don't think we should have a delta between beta1 and prod.

**Comment by callahad** [comment]
+1

**Comment by callahad** [comment]
I'll do this :)

**Comment by djc** [comment]
+1. @callahad I'd be happy to do this for you if you'd prefer! IMO it would be very good to clear things up around here.

It would be nice to clean up the branches here:

dev = prod + work from benadida (~16 months ago)
beta1 = dev + callahad-formatting + warner-crypto + loggedInUser
observer-updates = dev + callahad-formatting + warner-crypto + loggedInUser + 2 further loggedInUser/onmatch
dynamic-wellknown (#28) = dev + callahad-formatting + dynamic-wellknown

I also think we should maybe tag the current state of beta1 (or maybe beta1 + observer-updates and dynamic-wellknown) as beta1.

Given the current pace of movement on this, I think it makes sense to just develop on a master branch and tag things for different milestones, but that might just be me.
