### ISSUE TITLE
Impossible to run identity provider on domain name without A/AAAA record

### ISSUE THREAD

**Issue by jakllsch** [mozilla/id-specs#37]
Requiring an A/AAAA record on the root of a idenity-providing domain is unacceptable.  This could be worked around with browsers supporting SRV records, but that's probably never going to happen.

**Comment by ozten** [comment]
This might be a duplicate (from another repo).

I think @fmarier is working on DNS based solution to this bug in Issue#1523.

**Comment by fmarier** [comment]
DNS delegation is tracked in this bug: https://github.com/mozilla/browserid-roadmap/issues/38

Right now though, we've decided to punt on it because it would require DNSSEC: https://groups.google.com/d/topic/mozilla.dev.identity/dP44TDzBnhI/discussion
