### ISSUE TITLE
identity provider at a sub domain?

### ISSUE THREAD

**Issue by rsertelon** [mozilla/id-specs#38]
hi,

I wads reading the spec and all the doc about browserid; I find it great but I was wondering why did you chose the simple domain name for hosting the IDP.

it is clear that is@example.com should be provided by example.com but I was wondering why it could not be id.example.com.

In my mind, this would simplify deploying IDP software aside another service hosted at example.com

I was just wondering what could be the implications of my suggestion :-) 

thanks!

**Comment by fmarier** [comment]
You can host your IDP on a subdomain if you delegate to it from the main domain: https://developer.mozilla.org/en-US/Persona/.well-known-browserid#Delegated_Support

**Comment by rsertelon** [comment]
Hi @fmarier thanks for your answer. However, in the Checklist, right beneath the link you posted, it says:

`If delegating to another Identity Provider, the authority value is a bare domain name of the target IdP.`

From this sentence, it seems that I must use a bare domain name and not a subdomain. So it seems to me that it is not possible to use id.example.com as an IdP for example.com. Am I right, or is it possible anyways and the checklist is made for simple use cases?

**Comment by fmarier** [comment]
Looks like a bug in our documentation :)

`example.com` should be able to delegate to `login.example.com`, that's one of the things we want to enable with delegation. However, you can't delegate to `example.com/login` from the support document. It has to be a hostname only (with an optional port).

**Comment by rsertelon** [comment]
OK, that's perfect then :) Thanks for your answer ;)

**Comment by fmarier** [comment]
Great! If you find that it doesn't work, then let us know because it's a bug in Persona itself, not in the spec :)
