### ISSUE TITLE
Migration of IdP

### ISSUE THREAD

**Issue by rsertelon** [mozilla/id-specs#39]
Hi,

I'm trying to get my own identity provider work. In the mean time I was thinking about using the default login.persona.org IdP with my email address.

From what I've read, once I make my IdP work, all persona enabled websites will automatically use my IdP instead of the default one. Is it true?

Thanks for the help :)

**Comment by callahad** [comment]
That's correct :)

Persona always checks to see if your domain is an IdP first, before failing over to the login.persona.org fallback. As soon as yours is online, Persona will use it instead.
